INSERT INTO CLEAN.REVENUE (PARCELNUM, PRECINCT, MUNINAME, MARSHFIRE, ACCTTYPE, TAXYR, CURRTAX, PROPTAX, GEOM)
SELECT P.PARCELNUM,
	P.PRECINCT,
	P.MUNINAME,
	P.MARSHFIRE,
	T.ACCTTYPE,
	T.TAXYR,
	ROUND(T.ASSESSVAL * T.MILLLEVY / 1000, 2) CURRTAX,
	ROUND(T.ASSESSVAL * (T.MILLLEVY + 3.8) / 1000, 2) PROPTAX,
	P.GEOM
FROM CLEAN.TAXES T
JOIN CLEAN.LIBRARY_PARCELS P
ON T.PARCELNUM = P.PARCELNUM;