INSERT INTO CLEAN.REVENUE 
	(PARCELNUM, FULLADDRESS, INLIBDIST, PRECINCT, MUNINAME, MARSHFIRE, ACCTTYPE, TAXYR, ACTUALVAL, ASSESSVAL, MILLLEVY, CURRTAX, PROPTAX, REVENUE, GEOM)
SELECT P.PARCELNUM,
	T.FULLADDRESS,
	P.INLIBDIST,
	P.PRECINCT,
	P.MUNINAME,
	P.MARSHFIRE,
	T.ACCTTYPE,
	T.TAXYR,
	T.ACTUALVAL,
	T.ASSESSVAL,
	T.MILLLEVY,
	/*
	When an account is exempt, it does not pay property tax.

	When an account isn't in the district, its current and proposed taxes are
	the same, and no revenue is generated
	*/
	CASE
		WHEN T.ACCTTYPE = 'EXEMPT' THEN 0
		ELSE ROUND(T.ASSESSVAL * T.MILLLEVY / 1000, 2)
	END CURRTAX,
	CASE
		WHEN T.ACCTTYPE = 'EXEMPT' THEN 0
		WHEN P.INLIBDIST = FALSE THEN ROUND(T.ASSESSVAL * T.MILLLEVY / 1000, 2)
		ELSE ROUND(T.ASSESSVAL * (T.MILLLEVY + 3.5) / 1000, 2)
	END PROPTAX,
	CASE
		WHEN T.ACCTTYPE = 'EXEMPT' OR P.INLIBDIST = FALSE THEN 0
		ELSE ROUND(T.ASSESSVAL * 3.5 / 1000, 2)
	END REVENUE,
	P.GEOM
FROM CLEAN.TAXES T
JOIN CLEAN.LIBRARY_PARCELS P
ON T.PARCELNUM = P.PARCELNUM;